# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebMon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('content', models.TextField(default='')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='WebMon.Watch')),
            ],
        ),
    ]
